#### Configuration file ####

markets: # Supported: ASX, NASDAQ, NYSE. In a list so that scanner can work on multiple markets.
  - NASDAQ

pricing:
  min: 0.005  # minimum price to filter stocks when running scanner
  max: 500000  # maximum price to filter stocks when running scanner

filters:
  overextended_threshold_percent: 300  # skip stocks which went up more than this amount over a week
  minimum_volume_level: 350000  # min volume requirement (as 5-day moving average)
  stocks_only: True  # filters out ETFs and Funds
  volume_to_average: 0.7  # what volume is required on the last candle compared to average (used for MRI approach)
  range_percentage: 40  # there must be this difference in % (at least) between now and N weeks before to exclude weak stocks (used for MRI approach)
  range_over_weeks: 12  # over what time to apply (used for MRI approach)
  higher_than_n_last_candles: 4  # the green candle close must be higher than N last candles (used for MRI approach)

locality:
  tzinfo: Australia/Sydney
  shift_update_day: True  # shift update day by 1 by default, useful for being located in AU and trading US

simulator:  # note - does not apply to the legacy simulator, only works with the current one
  capital: 100000
  commission: 0
  simultaneous_positions: # variants to go through if several
    - 5
  failsafe_trigger_level: 0.15  # 15% to reach. Note: failsafe trigger is not actually used after thorough testing.
  failsafe_exit_level: 0.05  # 5% to throwback.

logging:
  gsheet_name: "Trading journal R&D 2024"
  gsheet_tab_name: "US_anx"
  gsheet_actual_price_col: "F"
  gsheet_columns: # Different for ANX and MRI (!)
    - stock
    - market
    - trade_type
    - entry_date
    - entry_price_planned
    - entry_price_actual
    - control_exit_date
    - exit_price_planned
    - main_exit_price
    - outcome
    - control_result_%
    - max_level_reached
    - exit_price_portion
    - threshold_1_expected_price
    - threshold_1_actual_price
    - threshold_1_exit_portion
    - threshold_2_expected_price
    - threshold_2_actual_price
    - threshold_2_exit_portion
    - threshold_3_expected_price
    - threshold_3_actual_price
    - threshold_3_exit_portion
    - ma_200_decreasing
    - weekly_mri_count
    - weekly_mri_direction
    - under_td_resistance
    - broken_td_resistance_before_entry
    - broken_td_resistance_after_entry
    - close_to_resistance
    - setup_type
    - fisher_distance
    - comments
