#####################################
#                                   #
#     🚀 SCANNER AND BASIC CONFIG   #
#                                   #
#####################################

markets: # Supported: ASX, NASDAQ, NYSE. In a list so that scanner can work on multiple markets.
  - NASDAQ

pricing:
  min: 0.005  # minimum price to filter stocks when running scanner
  max: 500000  # maximum price to filter stocks when running scanner

filters:
  overextended_threshold_percent: 300  # skip stocks which went up more than this amount over a week
  minimum_volume_level: 350000  # min volume requirement (as 5-day moving average)
  stocks_only: True  # filters out ETFs and Funds
  volume_to_average: 0.7  # what volume is required on the last candle compared to average (used for MRI approach)
  range_percentage: 40  # there must be this difference in % (at least) between now and N weeks before to exclude weak stocks (used for MRI approach)
  range_over_weeks: 12  # over what time to apply (used for MRI approach)
  higher_than_n_last_candles: 4  # the green candle close must be higher than N last candles (used for MRI approach)

locality:
  tzinfo: Australia/Sydney
  shift_update_day: True  # shift update day by 1 by default, useful for being located in AU and trading US

logging:
  gsheet_name: "Trading journal R&D 2024"
  gsheet_tab_name: "US_anx"
  gsheet_actual_price_col: "F"
  gsheet_columns: # columns in the spreadsheet
    - stock
    - market
    - trade_type
    - entry_date
    - entry_price_planned
    - entry_price_actual
    - initial_stop_loss
    - control_exit_date
    - exit_price_planned
    - main_exit_price
    - outcome
    - control_result_%
    - max_level_reached
    - exit_price_portion
    - threshold_1_expected_price
    - threshold_1_actual_price
    - threshold_1_exit_portion
    - threshold_2_expected_price
    - threshold_2_actual_price
    - threshold_2_exit_portion
    - threshold_3_expected_price
    - threshold_3_actual_price
    - threshold_3_exit_portion
    - ma_200_decreasing
    - weekly_mri_count
    - weekly_mri_direction
    - under_td_resistance
    - broken_td_resistance_before_entry
    - close_to_resistance
    - how_it_looks
    - fisher_daily
    - fisher_weekly
    - coppock_daily
    - coppock_weekly
    - comments

#==================================#
#                                  #
#    🧪 SIMULATOR PARAMETERS 🧪   #
#                                 #
#=================================#

simulator:
  capital: 10000
  commission: 1
  simultaneous_positions: # variants to go through, could be multiple to consider
#    - 1
    - 2

  # Settings for partial entries (always on as position management is important)
  # The first entry will be partial and then will need to wait for higher close
  first_entry_allocation: 0.5  # percentage of initial entry (0.5 is 50%)

  close_higher_percentage_variants: # close above bullish reference candle is needed for the second entry
#    - 0       # 0%
    - 0.0055  # 0.55%
#    - 0.01    # 1%
  # ^^^ to test variants later

  ### Stop-related behaviour
  stop_below_bullish_reference_variants: # this is for the level below the bullish candle's low 
#    - 0
#    - 0.01
    - 0.025

  stop_loss_management:  # take profit if the price increases to an amount X and then falls back
    price_increase_trigger: 0.1  # % increase from average entry price (e.g. 0.07 is 7%)
    new_stop_loss_level: 0.05     # X% above average entry price. the result was better with the value of 3%, need testing

  ### Filters to use

  #how_it_looks_filter: ["BR", "MBR"] # Note helpful - commented out
  # reference: ["BEAR", "BP", "BR", "BRTOBULL", 'EXTR', 'MBR', "SIDE", "STEP"]  # Filter based on the 'how_it_looks' column

  # close_to_resistance: ["Y", "N"] # not helpful, commented out

  numerical_filters:
    fisher_daily:
      min: -5000
      max: 5000
    fisher_weekly:
      min: -5000
      max: 5000
    coppock_daily:
      min: 0
      max: 5000
    coppock_weekly:
      min: 0
      max: 5000
    weekly_mri_count:
      min: 0
      max: 100

  ### Fisher distance related take profit
  fisher_distance_exit:
    enabled: true
    exit_proportion: 0.25
    max_exits: 3
    reentry_threshold: 0.6
    # ^^^ new threshold for allowing another exit. the value should go below zero and to this value again in order to take profit
    minimum_price_increase: 0.03  # X% minimum price increase for Fisher distance TP validity (from average entry price)

  ### Take profit variants
  take_profit_variants:

  - variant_name: "current"
    take_profit_values:
      - level: 1000%  # ridiculously high so that the baseline is kind of not taking profit
        exit_proportion: 50%
        move_stop_price: False

#  - variant_name: "baseline"  # similar to the current approach
#    take_profit_values:
#      - level: 50%
#        exit_proportion: 25%
#        move_stop_price: False
#      - level: 100%
#        exit_proportion: 25%
#        move_stop_price: False
#      - level: 150%
#        exit_proportion: 25%
#        move_stop_price: False
#
#  - variant_name: "conservative"
#    take_profit_values:
#      - level: 5%
#        exit_proportion: 25%
#        move_stop_price: False
#      - level: 10%
#        exit_proportion: 50%
#        move_stop_price: True
#        move_stop_from_tp_level: 5%  # this is a distance down from the take profit level (so if it pulls back X% from there)
#
#  - variant_name: "ultra_conservative"
#    take_profit_values:
#      - level: 10%
#        move_stop_price: False
#        exit_proportion: 100%

# 📝 NOTES
# Output will contain -> TRAILING PROFIT HIT for trailing profit and -> STOP LOSS HIT for stop losses
