#####################################
#                                   #
#     🚀 TRADING BOT CONFIG 🚀     #
#                                   #
#####################################

markets: # Supported: ASX, NASDAQ, NYSE. In a list so that scanner can work on multiple markets.
  - NASDAQ

pricing:
  min: 0.005  # minimum price to filter stocks when running scanner
  max: 500000  # maximum price to filter stocks when running scanner

filters:
  overextended_threshold_percent: 300  # skip stocks which went up more than this amount over a week
  minimum_volume_level: 350000  # min volume requirement (as 5-day moving average)
  stocks_only: True  # filters out ETFs and Funds
  volume_to_average: 0.7  # what volume is required on the last candle compared to average (used for MRI approach)
  range_percentage: 40  # there must be this difference in % (at least) between now and N weeks before to exclude weak stocks (used for MRI approach)
  range_over_weeks: 12  # over what time to apply (used for MRI approach)
  higher_than_n_last_candles: 4  # the green candle close must be higher than N last candles (used for MRI approach)

locality:
  tzinfo: Australia/Sydney
  shift_update_day: True  # shift update day by 1 by default, useful for being located in AU and trading US

logging:
  gsheet_name: "Trading journal R&D 2024"
  gsheet_tab_name: "US_anx"
  gsheet_actual_price_col: "F"
  gsheet_columns: # Different for ANX and MRI (!)
    - stock
    - market
    - trade_type
    - entry_date
    - entry_price_planned
    - entry_price_actual
    - control_exit_date
    - exit_price_planned
    - main_exit_price
    - outcome
    - control_result_%
    - max_level_reached
    - exit_price_portion
    - threshold_1_expected_price
    - threshold_1_actual_price
    - threshold_1_exit_portion
    - threshold_2_expected_price
    - threshold_2_actual_price
    - threshold_2_exit_portion
    - threshold_3_expected_price
    - threshold_3_actual_price
    - threshold_3_exit_portion
    - ma_200_decreasing
    - weekly_mri_count
    - weekly_mri_direction
    - under_td_resistance
    - broken_td_resistance_before_entry
    - close_to_resistance
    - how_it_looks
    - fisher_daily
    - fisher_weekly
    - coppock_daily
    - coppock_weekly
    - comments

#==================================#
#                                  #
#    🧪 SIMULATOR PARAMETERS 🧪   #
#                                 #
#=================================#

simulator:
  capital: 10000
  commission: 1
  simultaneous_positions: # variants to go through, could be multiple to consider
    - 4
  #  - 5
  failsafe_trigger_level: 0.15  # 15% to reach. Note: failsafe trigger is not actually used after thorough testing, remove
  failsafe_exit_level: 0.05  # 5% to throwback.

  ### Stop-related behaviour
  stop_loss_level: 0.1
  # stop loss to fully exit. this is calculated from the candle previous to entry day (when we have signal) low
  # ^^^ decimal representation e.g. 0.05 equals 5%
  # seems that 5% may be too conservative, needs further testing

  ### Filters to use
  numerical_filters:
    fisher_daily:
      min: -500
      max: 500
    fisher_weekly:
      min: -500
      max: 500

  ### Take profit variants
  take_profit_variants:

#  - variant_name: "current"
#    take_profit_values:
#      - level: 1000%  # ridiculously high so that the baseline is kind of not taking profit; not using
#        exit_proportion: 100%

  - variant_name: "baseline"  # similar to the current approach
    take_profit_values:
      - level: 50%
        exit_proportion: 25%
        move_stop_price: False
      - level: 100%
        exit_proportion: 25%
        move_stop_price: False
      - level: 150%
        exit_proportion: 25%
        move_stop_price: False

#  - variant_name: "conservative"
#    take_profit_values:
#      - level: 5%
#        exit_proportion: 25%
#        move_stop_price: False
#      - level: 10%
#        exit_proportion: 25%
#        move_stop_price: True
#        move_stop_from_tp_level: 5%  # this is a distance down from the take profit level (so if it pulls back X% from there)

#  - variant_name: "ultra_conservative"  # similar to the current approach
#    take_profit_values:
#      - level: 10%
#        exit_proportion: 100%

      # Notes 📝
      # Output will contain TRAILING PROFIT HIT for trailing profit
      # STOP LOSS HIT for stop losses
